name: Cron

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

env:
  FORCE_COLOR: 1
  PIP_DISABLE_PIP_VERSION_CHECK: 1

permissions:
  contents: read

jobs:
  cron:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: pip
      - name: Generate
        run: |
          python -m pip install -r requirements.txt
          python last-updated.py --csv >> last-updated.csv
          # Deduplicate
          awk -i inplace '!seen[$0]++' last-updated.csv
      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add last-updated.csv
          git commit -m "Updates for $(date)" || true
          git push
